
server:
  port: 9901

spring:
  application:
    name: rick-and-morti-api
  datasource:
    driveClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/persondb?autoconnect=true"
    username: "root"
    password: "1qaz1qaz"
  flyway:
    enabled: true
